# Site settings
title: Naoki Itsui / Master Student
email: naoki.itsui_at_issp.u-tokyo.ac.jp
description: Academic webpage of Naoki Itsui
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Naoki Itsui<br/>
  Master student at <a href="https://oka.issp.u-tokyo.ac.jp/index_eng.htm" target="_blank"> Oka group</a><br/>
  Institute for Solid State Physics<br/>
  University of Tokyo

location: >
  #A430a<br/>
  Institute for Solid State Physics,<br/>
  University of Tokyo,<br/>
  5-1-5 Kashiwanoha, Kashiwa,<br/>
  Chiba, Japan, 277-8581

contact: >
  <a href="mailto:naoki.itsui@issp.u-tokyo.ac.jp" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Naoki via email</a> <br/>
  <a href="https://github.com/sbryngelson/academic-website-template" target="_blank"><i class="fa fa-github fa-1x"></i> Use this site as a template!</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: research
  - name: publications
  - name: talks
  - name: Notes
  - name: blogs
  - name: links

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
